fruits = ('apple','banana','kiwi','orange')
print(fruits[3])
print(fruits[-2])
print(fruits[1:3])
print(fruits[2:])
print(fruits[2:10])
print(fruits)
# y = list(fruits)
# print(y)
# fruits = tuple(y)
# print(fruits)
fruits1 = ('graps','lichi')
fruits += fruits1
print(fruits)